
name: Deployments PR verify

on:
  push:
    branches: [ main ]
    
  pull_request:
    paths:
      - 'deployments/**'

jobs:
  get_changes:
    uses: firestartr-test/.reusable_workflows/.github/workflows/state-repo-analyze-changes.yaml@main
    with:
      path: 'deployments'
      is-deployment: true

  pr-verify:
    needs: get_changes
    
    strategy:
      matrix:
        environments: ${{ fromJson(needs.get_changes.outputs.changes) }}

    uses: firestartr-test/.reusable_workflows/.github/workflows/state-repo-analyze-changes.yaml@main