
name: Hello World Matrix

on:
  push:
    branches: [ main ]
    
  pull_request:
    paths:
      - 'deployments/**'

jobs:
  get_changes:
    uses: firestartr-test/.reusable_workflows/.github/workflows/state-repo-analyze-changes.yaml@main
    with:
      path: 'deployments'
      is-deployment: true

  pr-verify:
    runs-on: ubuntu-latest
    needs: get_changes
    
    strategy:
      matrix:
        environments: ${{ fromJson(needs.get_changes.outputs.changes) }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run hello world script
      run: |
        echo "Hello, World! Running on Node.js version ${{ matrix.environments.name }}"
