
name: Hello World Matrix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  call-workflow-in-another-repo:
    uses: firestartr-test/.reusable_workflows/.github/workflows/state-repo-analyze-changes.yaml@main
  
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        environments: [
          {
            name: "predev",
            apps: {
              "tenant/app"
            }
          },
          {
            name: "pre",
            apps: {
              "tenant2/app"
            }
          },
          {
            name: "pro",
            apps: {
              "tenant3/app",
              "tenant4/app"
            }
          }
        ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run hello world script
      run: |
        echo "Hello, World! Running on Node.js version ${{ matrix.environments.name }}"
